title: Lightcodepedia
description: A GitHub Pages site

# remote_theme: just-the-docs/just-the-docs   # ← add this
remote_theme: pages-themes/cayman@v0.2.0
plugins: [jekyll-remote-theme] 

defaults:
  - scope:
      path: "modules"   # only /modules
    values:
      layout: null      # don’t wrap them in HTML

# Important: tell Jekyll to copy .yaml as-is
include:
  - modules
  - modules/*.yaml

mermaid:
  # pick any version listed on jsDelivr
  version: "10.9.1"
